2020-07-08-13.03

diff --git a/build/Dockerfile-php7.2-nodejs-dropbear b/build/Dockerfile-php7.2-nodejs-dropbear
--- a/build/Dockerfile-php7.2-nodejs-dropbear
+++ b/build/Dockerfile-php7.2-nodejs-dropbear
@@ -1,22 +1,34 @@
 #FROM bylexus/apache-php7 #FROM registrydocker/php7.2-apache
-FROM ubuntu:bionic
+#FROM ubuntu:bionic
+FROM  thefoundation/upgraded-operating-systems:ubuntu-bionic
+
+
+ARG APP_AUTOAPTPROXY
+RUN if [ "${APP_AUTOAPTPROXY}" = "true" ]; then export ENV=debug;echo "auto-apt-proxy ENABLED AT BUILD";else echo "NO APT PROXY (set APP_AUTOAPTPROXY=true in .env to activate)"; fi
+RUN if [ "${APP_AUTOAPTPROXY}" = "true" ]; then apt-get update &&  apt-get autoremove -y --force-yes &&  /bin/bash /i.sh qclean  ;fi
+ARG APP_AUTOAPTPROXY=false
+
+ARG APT_HTTP_PROXY_URL
+RUN if [ "x$APT_HTTP_PROXY_URL" = "x" ] ; then echo Argument not provided ;else ( echo 'Acquire::http::Proxy "'${APT_HTTP_PROXY_URL}'/";' ;echo 'PassThroughPattern: ^(.*):443$;';)| tee /etc/apt/apt.conf.d/10-proxy   ;fi
 
 RUN /bin/mkdir -p /root/.bin/
 COPY docker-install.sh /root/.bin/
-RUN /bin/bash /root/.bin/docker-install.sh fixapt
+RUN ln -s /root/.bin/docker-install.sh /i.sh
 
+## OVERWRITTEN IN RUN.sh if APP_TIMEZONE set
+RUN /bin/ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
 ARG APP_DEBUG
+
 RUN if [ "${APP_DEBUG}" = "true" ]; then export ENV=debug;echo "DEBUG MODE ACTIVATED AT BUILD";else echo "NORMAL MODE (set APP_DEBUG=true in .env to activate)"; fi
 ARG APP_DEBUG=false
 
-
-RUN apt-get update && /bin/bash /root/.bin/docker-install.sh fixapt && \
+RUN apt-get update && /bin/bash /i.sh fixapt && \
     apt-get dist-upgrade -y
 
 ## OVERWRITTEN IN RUN.sh if APP_TIMEZONE set
 RUN /bin/ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
 
-RUN  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update   && apt-get dist-upgrade -y &&  apt-get install -y  --no-install-recommends software-properties-common && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php  && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/apache2 && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/pkg-gearman && /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update &&  apt-get install -y --no-install-recommends \
+RUN  /bin/bash /i.sh fixapt && apt-get update   && apt-get dist-upgrade -y &&  apt-get install -y  --no-install-recommends software-properties-common && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php  && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/apache2 && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/pkg-gearman && /bin/bash /i.sh fixapt && apt-get update &&  apt-get install -y --no-install-recommends \
       apache2 zip tar \
       php7.2 php7.2-cli php7.2-intl \
       libapache2-mod-php7.2 \
@@ -28,15 +40,16 @@ RUN  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update   && apt-ge
       php7.2-gd \
       php7.2-imagick \
       php7.2-ldap \
-      openssh-sftp-server dropbear-run dropbear-bin wget curl ca-certificates rsync nano vim psmisc procps git cron gcc make autoconf libc-dev pkg-config libmcrypt-dev  php-pear php7.2-dev msmtp msmtp-mta software-properties-common &&  /bin/bash /root/.bin/docker-install.sh fullclean
+      openssh-sftp-server dropbear-run dropbear-bin wget curl ca-certificates rsync nano vim psmisc procps git cron gcc make autoconf libc-dev pkg-config libmcrypt-dev  php-pear php7.2-dev msmtp msmtp-mta software-properties-common && pecl channel-update pecl.php.net &&  /bin/bash /i.sh fullclean
 
 RUN echo INSTALL php-mcrypt
-RUN pecl install mcrypt-1.0.1 &&  /bin/bash /root/.bin/docker-install.sh fullclean
-RUN a2enmod proxy ssl proxy_http remoteip
-
+RUN apt-get install php7.2-dev && pecl install mcrypt-1.0.1 &&  apt-get purge php7.2-dev && /bin/bash /i.sh fullclean
 #RUN echo extension=$(find /usr/lib/php -name "mcrypt.so")  |tee /etc/php/7.2/apache2/conf.d/mcrypt.ini /etc/php/7.2/cli/conf.d/mcrypt.ini
 RUN bash -c "echo extension="$(find /usr/lib/php/ -name "mcrypt.so" |head -n1) | tee /etc/php/7.2/apache2/conf.d/mcrypt.ini /etc/php/7.2/cli/conf.d/mcrypt.ini
 RUN test -d /etc/php/7.2/mods-available || /bin/mkdir /etc/php/7.2/mods-available && bash -c "echo extension="$(find /usr/lib/php/ -name "mcrypt.so" |head -n1) |tee /etc/php/7.2/mods-available/mcrypt.ini
+
+
+RUN a2enmod proxy ssl proxy_http remoteip
 
 RUN { \
                 echo 'opcache.memory_consumption=128'; \
@@ -54,16 +67,18 @@ RUN apt-get -y install nodejs npm
 
 ##SERVICES ( order of entries with ARG= decide on position in increasin-feature build)
 ARG INSTALL_IMAGICK
-ARG INSTALL_MARIADB
 ARG INSTALL_REDIS
+ARG INSTALL_MARIADB
+
 ARG INSTALL_NPM
 ARG INSTALL_MONGODB
 ARG INSTALL_RABBITMQ
 ARG INSTALL_SWISH
 
 ARG INSTALL_IMAGICK=true
-ARG INSTALL_MARIADB=true
 ARG INSTALL_REDIS=true
+ARG INSTALL_MARIADB=true
+
 ARG INSTALL_NPM=false
 ARG INSTALL_MONGODB=false
 ARG INSTALL_RABBITMQ=false
@@ -71,48 +86,41 @@ ARG INSTALL_SWISH=false
 
 RUN echo "installer selection: mariadb:"${INSTALL_MARIADB}" mongodb: "${INSTALL_MONGODB}" RABBITMQ: "${INSTALL_RABBITMQ}" IMAGICK:"${INSTALL_IMAGICK}
 
-RUN if [ "${INSTALL_IMAGICK}" = "true"   ]; then echo "+Imagick"; /bin/bash /root/.bin/docker-install.sh imagemagick && /bin/bash /root/.bin/docker-install.sh fixapt && /bin/bash /root/.bin/docker-install.sh fullclean  ; else echo "NOT INSTALLING imagemagick, set INSTALL_IMAGICK=true in .env to install "; fi
-RUN if [ "${INSTALL_MARIADB}" = "true"   ]; then apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 && LC_ALL=C.UTF-8 add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirrors.n-ix.net/mariadb/repo/10.3/ubuntu bionic main' && apt-get update && export DEBIAN_FRONTEND=noninteractive &&  apt-get -y install --no-install-recommends mariadb-server mariadb-client &&  /bin/bash /root/.bin/docker-install.sh fullclean   ;else echo "NOT INSTALLING MYSQL(mariadb), set INSTALL_MARIADB=true in .env to install ";echo VALUE IS ;echo "${INSTALL_MARIADB}"; fi
-RUN if [ "${INSTALL_MONGODB}" = "true"   ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends mongodb-server mongodb-clients &&  /bin/bash /root/.bin/docker-install.sh fullclean  ;else echo "NOT INSTALLING MONGODB, set INSTALL_MONGODB=true in .env to install "; fi
-RUN if [ "${INSTALL_RABBITMQ}" = "true"  ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends rabbitmq-server &&  /bin/bash /root/.bin/docker-install.sh fullclean  ;else echo "NOT INSTALLING RABBITMQ, set INSTALL_RABBITMQ=true in .env to install "; fi
-RUN if [ "${INSTALL_REDIS}" = "true"     ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends redis-server redis-sentinel redis-tools &&  /bin/bash /root/.bin/docker-install.sh fullclean  ;else echo "NOT INSTALLING REDIS, set INSTALL_REDIS=true in .env to install "; fi
-RUN if [ "${INSTALL_SWISH}" = "true"     ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends swish-e &&  /bin/bash /root/.bin/docker-install.sh fullclean  ;else echo "NOT INSTALLING swish-e, set INSTALL_SWISH=true in .env to install "; fi
+RUN if [ "${INSTALL_IMAGICK}" = "true"   ]; then echo "+Imagick"; /bin/bash /i.sh imagemagick && /bin/bash /i.sh fixapt && apt-get update && /bin/bash /i.sh fullclean  ; else echo "NOT INSTALLING imagemagick, set INSTALL_IMAGICK=true in .env to install "; fi
+RUN if [ "${INSTALL_MONGODB}" = "true"   ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends mongodb-server mongodb-clients &&  /bin/bash /i.sh fullclean  ;else echo "NOT INSTALLING MONGODB, set INSTALL_MONGODB=true in .env to install "; fi
+RUN if [ "${INSTALL_RABBITMQ}" = "true"  ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends rabbitmq-server &&  /bin/bash /i.sh fullclean  ;else echo "NOT INSTALLING RABBITMQ, set INSTALL_RABBITMQ=true in .env to install "; fi
+RUN if [ "${INSTALL_REDIS}" = "true"     ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends redis-server redis-sentinel redis-tools &&  /bin/bash /i.sh fullclean  ;else echo "NOT INSTALLING REDIS, set INSTALL_REDIS=true in .env to install "; fi
+RUN if [ "${INSTALL_NPM}" = "true"       ]; then apt-get update && apt-get -y install --no-install-recommends npm ;else echo "NOT INSTALLING npm, set INSTALL_NPM=true in .env to install "; fi
+RUN if [ "${INSTALL_SWISH}" = "true"     ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends swish-e &&  /bin/bash /i.sh fullclean  ;else echo "NOT INSTALLING swish-e, set INSTALL_SWISH=true in .env to install "; fi
 
-RUN   apt-get clean && \
-      rm /var/lib/apt/lists/*_*
+RUN if [ "${INSTALL_MARIADB}" = "true"   ]; then apt-get update  && apt-get install -y  --no-install-recommends  dirmngr software-properties-common || true  &&   apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 && LC_ALL=C.UTF-8 add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirrors.n-ix.net/mariadb/repo/10.3/ubuntu bionic main' && apt-get update && export DEBIAN_FRONTEND=noninteractive &&  apt-get -y install --no-install-recommends mariadb-server mariadb-client &&  /bin/bash /i.sh fullclean   ;else echo "NOT INSTALLING MYSQL(mariadb), set INSTALL_MARIADB=true in .env to install ";echo VALUE IS ;echo "${INSTALL_MARIADB}"; fi
 
-# Remove keys
-RUN rm /etc/dropbear/dropbear_dss_host_key /etc/dropbear/dropbear_rsa_host_key /etc/dropbear/dropbear_ecdsa_host_key || true
+#######
+COPY pool-www.conf /root/www.conf
+#######
 
-RUN phpenmod mcrypt && a2enmod rewrite expires ssl && a2dismod mpm_event mpm_worker && a2enmod mpm_prefork
-RUN a2enmod remoteip && a2ensite default-ssl && a2ensite 000-default && ls -lh1 /etc/apache2/sites*/*
+COPY run-dropbear.sh /usr/local/bin/run.sh
+COPY supervisord.conf /etc/supervisor/supervisord.conf
+COPY run-apache.sh /run-apache.sh
+RUN chmod +x /usr/local/bin/run.sh
+ 
+## INSTALL UTiLS , Fix Apache , rectify www-data , fpm socket etc
+RUN /bin/bash /i.sh util && /bin/bash /i.sh apache &&  /bin/bash /i.sh wwwdata
 
-RUN sed 's/DocumentRoot \/var\/www$/DocumentRoot \/var\/www\/html/g' /etc/apache2/sites-enabled/* -i
-##redirect other vhosts
-RUN sed 's/other_vhosts_access.log/access.log/g' -i /etc/apache2/conf-enabled/other-vhosts-access-log.conf
 
-RUN sed 's/\/VirtualHost/Directory "\/var\/www"> \n    Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch\n    AllowOverride All\n<\/Directory>\n     <\/VirtualHost/g' -i /etc/apache2/sites-available/000-default.conf && \
-                sed 's/\/VirtualHost/Directory "\/var\/www"> \n    Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch\n    AllowOverride All\n<\/Directory>\n     <\/VirtualHost/g' -i /etc/apache2/sites-available/default-ssl.conf && \
-		cp -aurv /etc/apache2/sites-available/ /etc/apache2/sites-available.default ;ln -sf /etc/apache2/sites-available/* /etc/apache2/sites-enabled/
+##cleanup stage will be always executed due to random file , so upgrades happen every build ( no docker cache)
+RUN head -c 5 /dev/random > ignore_this_file && apt-get update && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  e2fsprogs python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev ) && /bin/bash /i.sh cleanup
 
 #EXPOSE 80
 EXPOSE 443
 
-##fixx www-data userid and only enable sftp for them (bind mount /etc/shells and run "usermod -s /bin/bash www-data" for www-data user login )
-RUN sed 's/^www-data:x:1000/www-data:x:33/g' /etc/passwd -i && usermod -s /usr/lib/openssh/sftp-server www-data && echo /usr/lib/openssh/sftp-server >> /etc/shells
-
-##userdirs  ## ssh keys incl. tricky dropbear permissions
-RUN ln -s /var/www/html /root/ &&  /bin/mkdir -p /var/www/.ssh /var/www/include /var/www/include_local && chown www-data /var/www/ -R && /bin/mkdir /root/.ssh && touch /root/.ssh/authorized_keys &&  touch /var/www/.ssh/authorized_keys && chown root:root /var/www/.ssh /var/www/.ssh/authorized_keys && chmod go-rw  /root/.ssh/authorized_keys /root/.ssh /var/www/.ssh /var/www/.ssh/authorized_keys
-
-#disable catchall document root
-RUN sed 's/.\+DocumentRoot.\+//g' -i /etc/apache2/apache2.conf
-
-#INSTALL & PATCH MSMTP-CRON
-COPY run-dropbear.sh /usr/local/bin/run.sh
+##
 COPY msmtp-cron-sendmail/sendmail /usr/sbin/sendmail.cron
-RUN chmod +x /usr/sbin/sendmail.cron /usr/local/bin/run.sh
+RUN chmod +x /usr/sbin/sendmail.cron
 
+
+RUN /bin/bash -c "date -u +%Y-%m-%d_%H.%M |tee -a /etc/container-build-time" && /bin/bash -c "test -f /etc/apt/apt.conf.d/10-proxy && rm /etc/apt/apt.conf.d/10-proxy;true"
 WORKDIR /var/www
-HEALTHCHECK CMD /usr/bin/curl --fail -H "User-Agent: docker-health-check/over9000" -kL https://127.0.0.1/ || exit 1
+HEALTHCHECK CMD /usr/bin/curl--fail -H "User-Agent: docker-health-check/over9000" -kL https://127.0.0.1/ || exit 1
 CMD ["/bin/bash","/usr/local/bin/run.sh"]
 MAINTAINER commits@hideaddress.net
