2021-01-22-05.35

diff --git a/build/Dockerfile-php7.2-dropbear-fpm b/build/Dockerfile-php7.2-dropbear-fpm
--- a/build/Dockerfile-php7.2-dropbear-fpm
+++ b/build/Dockerfile-php7.2-dropbear-fpm
@@ -109,7 +109,9 @@ COPY 000-default.conf default-ssl.conf /etc/apache2/sites-enabled/
 COPY 000-default.conf default-ssl.conf /etc/apache2/sites-available.default/
 
 WORKDIR /var/www
-HEALTHCHECK CMD /usr/bin/curl --fail -H "User-Agent: docker-health-check/over9000" -kL https://127.0.0.1/ || exit 1
+#HEALTHCHECK CMD /usr/bin/curl --fail -H "User-Agent: docker-health-check/over9000" -kL https://127.0.0.1/ || exit 1
+HEALTHCHECK CMD /bin/bash /healthcmd.sh
+
 CMD ["/bin/bash","/usr/local/bin/run.sh"]
 MAINTAINER commits@hideaddress.net
 
@@ -118,7 +120,7 @@ MAINTAINER commits@hideaddress.net
 RUN head -c 5 /dev/random > ignore_this_file && apt-get update && apt-get -y -f install && dpkg --configure -a && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev ) && /bin/bash /i.sh cleanup
 RUN rm /etc/apt/apt.conf.d/10-proxy|| true
 
-COPY supervisor-logger x-finalcommands.sh _0_crt-snakeoil.sh  _0_fix-composer.sh  _0_fix-dropbear.sh  _0_get-toolkit.sh  _0_sys-mailprep.sh _2_supervisor_prep.sh _1_php-initprep.sh _1_php-initfirst.sh _1_php-initfpm.sh _1_sql-initprep.sh  _1_sys-mongopre.sh  _1_www-userprep.sh _3_logfilter_apache.sh /
+COPY healthcmd.sh supervisor-logger x-finalcommands.sh _0_crt-snakeoil.sh  _0_fix-composer.sh  _0_fix-dropbear.sh  _0_get-toolkit.sh  _0_sys-mailprep.sh _2_supervisor_prep.sh _1_php-initprep.sh _1_php-initfirst.sh _1_php-initfpm.sh _1_sql-initprep.sh  _1_sys-mongopre.sh  _1_www-userprep.sh _3_logfilter_apache.sh /
 
 #COPY x-finalcommands.sh /root/.x_finalcmd.sh
 COPY run-dropbear.sh /usr/local/bin/run.sh
