2021-01-18-19.11

diff --git a/build/Dockerfile-php7.4-dropbear-fpm b/build/Dockerfile-php7.4-dropbear-fpm
--- a/build/Dockerfile-php7.4-dropbear-fpm
+++ b/build/Dockerfile-php7.4-dropbear-fpm
@@ -84,40 +84,41 @@ RUN which apt-get &&  if [ "${WEBSERVER}" = "apache"     ]; then  apt-get update
 RUN which apt-get && if [ "${WEBSERVER}" = "nginx"     ]; then   apt-get update >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends nginx-full ;fi
 
 
+
 #######
 COPY pool-www.conf /root/www.conf
 #######
 ## INSTALL UTiLS , Fix Apache , rectify www-data , fpm socket etc
 RUN  /bin/bash /i.sh wwwdata
 
-COPY supervisord.conf /etc/supervisor/supervisord.conf
-COPY run-apache.sh /run-apache.sh
-
-#SQUASH#
-##cleanup stage will be always executed due to random file , so upgrades happen every build ( no docker cache)
-RUN head -c 5 /dev/random > ignore_this_file && apt-get update && apt-get -y -f install && dpkg --configure -a && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev ) && /bin/bash /i.sh cleanup
-RUN rm /etc/apt/apt.conf.d/10-proxy|| true
-#EXPOSE 80
-EXPOSE 443
-
 ##
 COPY msmtp-cron-sendmail/sendmail /usr/sbin/sendmail.cron
 RUN chmod +x /usr/sbin/sendmail.cron
 
+COPY supervisord.conf /etc/supervisor/supervisord.conf
+COPY run-apache.sh /run-apache.sh
+
 
 RUN /bin/bash -c "date -u +%Y-%m-%d_%H.%M |tee -a /etc/container-build-time" && /bin/bash -c "test -f /etc/apt/apt.conf.d/10-proxy && rm /etc/apt/apt.conf.d/10-proxy;true"
 RUN mkdir  /etc/apache-extra-config-varwww/ /etc/apache-extra-config-vhost/ /etc/apache-extra-config-security/
-
 COPY 000-default.conf default-ssl.conf /etc/apache2/sites-available/
 COPY 000-default.conf default-ssl.conf /etc/apache2/sites-enabled/
 COPY 000-default.conf default-ssl.conf /etc/apache2/sites-available.default/
-COPY supervisor-logger x-finalcommands.sh _0_crt-snakeoil.sh  _0_fix-composer.sh  _0_fix-dropbear.sh  _0_get-toolkit.sh  _0_sys-mailprep.sh  _1_php-initprep.sh  _1_sql-initprep.sh  _1_sys-mongopre.sh  _1_www-userprep.sh /
-COPY x-finalcommands.sh /root/
-COPY run-dropbear.sh /usr/local/bin/run.sh
-RUN chmod +x /usr/local/bin/run.sh /supervisor-logger
-RUN /bin/bash /root/x-finalcommands.sh
 
 WORKDIR /var/www
 HEALTHCHECK CMD /usr/bin/curl --fail -H "User-Agent: docker-health-check/over9000" -kL https://127.0.0.1/ || exit 1
 CMD ["/bin/bash","/usr/local/bin/run.sh"]
 MAINTAINER commits@hideaddress.net
+
+#SQUASH#
+##cleanup stage will be always executed due to random file , so upgrades happen every build ( no docker cache)
+RUN head -c 5 /dev/random > ignore_this_file && apt-get update && apt-get -y -f install && dpkg --configure -a && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev ) && /bin/bash /i.sh cleanup
+RUN rm /etc/apt/apt.conf.d/10-proxy|| true
+
+COPY supervisor-logger x-finalcommands.sh _0_crt-snakeoil.sh  _0_fix-composer.sh  _0_fix-dropbear.sh  _0_get-toolkit.sh  _0_sys-mailprep.sh  _1_php-initprep.sh  _1_sql-initprep.sh  _1_sys-mongopre.sh  _1_www-userprep.sh /
+#COPY x-finalcommands.sh /root/.x_finalcmd.sh
+COPY run-dropbear.sh /usr/local/bin/run.sh
+RUN chmod +x /usr/local/bin/run.sh /supervisor-logger
+RUN /bin/bash /root/x-finalcommands.sh
+#EXPOSE 80
+EXPOSE 443
