2021-01-24-02.50

diff --git a/build/Dockerfile-php7.2-dropbear-fpm b/build/Dockerfile-php7.2-dropbear-fpm
--- a/build/Dockerfile-php7.2-dropbear-fpm
+++ b/build/Dockerfile-php7.2-dropbear-fpm
@@ -64,29 +64,8 @@ RUN  echo "installing php"${PHP_VERSION} &&  apt-get update >/dev/null &&  DEBIA
 
 RUN php --version |grep "${PHP_VERSION}"
 
-COPY docker-install.sh /root/.bin/
-
-##########
-
-##without php-cli , step will fail ( version detection )
-RUN /bin/bash /i.sh php-basic && if [ "${INSTALL_IMAGICK}" = "true"   ]; then \
-            echo "+Imagick"; /bin/bash /i.sh imagemagick && \
-            /bin/bash /i.sh fixapt && apt-get update  ; \
-          else \
-            echo "NOT INSTALLING imagemagick, set INSTALL_IMAGICK=true in .env to install "; fi || true &&  \
-            /bin/bash /i.sh php-fpm && echo "PHP installs done"
-
-RUN  if [ "${WEBSERVER}" = "apache"     ]; then \
-                           which apt-get 2>&1 |grep apt-get && apt-get update >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends apache2 && /bin/bash /i.sh apache  ;fi
-RUN  if [ "${WEBSERVER}" = "nginx"      ]; then \
-                           which apt-get 2>&1 |grep apt-get && apt-get update >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends nginx-full ;fi
-
-#######
+####### copy stage
 COPY pool-www.conf /root/www.conf
-#######
-## INSTALL UTiLS , Fix Apache , rectify www-data , fpm socket etc
-RUN /bin/bash /i.sh fixapt && apt-get update   &&  apt-get -y --no-install-recommends install memcached && /bin/bash /i.sh wwwdata
-
 ##
 COPY msmtp-cron-sendmail/sendmail /usr/sbin/sendmail.cron
 RUN chmod +x /usr/sbin/sendmail.cron
@@ -94,6 +73,26 @@ RUN chmod +x /usr/sbin/sendmail.cron
 COPY supervisord.conf /etc/supervisor/supervisord.conf
 COPY run-apache.sh /run-apache.sh
 
+
+#######
+
+COPY docker-install.sh /root/.bin/
+
+##########
+
+##without php-cli , step will fail ( version detection )
+RUN /bin/bash /i.sh php-basic && if [ "${INSTALL_IMAGICK}" = "true"   ]; then \
+            echo "+Imagick"; /bin/bash /i.sh imagemagick ; \
+          else \
+            echo "NOT INSTALLING imagemagick, set INSTALL_IMAGICK=true in .env to install "; fi || true &&  \
+            /bin/bash /i.sh php-fpm && echo "PHP installs done"
+  if [ "${WEBSERVER}" = "apache"     ]; then \
+                           which apt-get 2>&1 |grep apt-get && apt-get update >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends apache2 && /bin/bash /i.sh apache  ;fi && \
+  if [ "${WEBSERVER}" = "nginx"      ]; then \
+                           which apt-get 2>&1 |grep apt-get && apt-get update >/dev/null && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends nginx-full ;fi && \
+RUN /bin/bash /i.sh fixapt && apt-get update   &&  apt-get -y --no-install-recommends install memcached && /bin/bash /i.sh wwwdata
+
+## ABOVE: INSTALL UTiLS , Fix Apache , rectify www-data , fpm socket etc
 
 RUN /bin/bash -c "date -u +%Y-%m-%d_%H.%M |tee -a /etc/container-build-time" && /bin/bash -c "test -f /etc/apt/apt.conf.d/10-proxy && rm /etc/apt/apt.conf.d/10-proxy;true"
 RUN mkdir  /etc/apache-extra-config-varwww/ /etc/apache-extra-config-vhost/ /etc/apache-extra-config-security/  /etc/apache2/sites-available.default/
@@ -110,7 +109,7 @@ MAINTAINER commits@hideaddress.net
 
 #SQUASH#
 ##cleanup stage will be always executed due to random file , so upgrades happen every build ( no docker cache)
-RUN head -c 5 /dev/random > ignore_this_file && apt-get update && apt-get -y -f install && dpkg --configure -a && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev ) && /bin/bash /i.sh cleanup
+RUN head -c 5 /dev/random > /usr/lib/ignore_this_file && apt-get update && apt-get -y -f install && dpkg --configure -a && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev ) && /bin/bash /i.sh cleanup
 RUN rm /etc/apt/apt.conf.d/10-proxy|| true
 
 COPY healthcheck.sh shutdown.sh supervisor-logger x-finalcommands.sh _0_crt-snakeoil.sh  _0_fix-composer.sh  _0_fix-dropbear.sh  _0_get-toolkit.sh  _0_sys-mailprep.sh _2_supervisor_prep.sh _1_php-initprep.sh _1_php-initfirst.sh _1_php-initfpm.sh _1_sql-initprep.sh  _1_sys-mongopre.sh  _1_www-userprep.sh _3_logfilter_apache.sh /
