2020-03-11_11.48

diff --git a/build/Dockerfile-php5-dropbear b/build/Dockerfile-php5-dropbear
--- a/build/Dockerfile-php5-dropbear
+++ b/build/Dockerfile-php5-dropbear
@@ -1,1 +1,117 @@
-Dockerfile-php5.6-dropbear
+FROM registrydocker/php5.6-apache
+#FROM eboraas/apache-php
+
+ARG APP_DEBUG
+RUN if [ "${APP_DEBUG}" = "true" ]; then export ENV=debug;echo "DEBUG MODE ACTIVATED AT BUILD";else echo "NORMAL MODE (set APP_DEBUG=true in .env to activate)"; fi
+ARG APP_DEBUG=false
+
+RUN dpkg --get-selections |grep -v deinstall|grep php7.0- -q  && (apt-get -y purge php7.0-*  ) || true
+RUN dpkg --get-selections |grep -v deinstall|grep php7.1- -q  && (apt-get -y purge php7.1-*  ) || true
+RUN dpkg --get-selections |grep -v deinstall|grep php7.2- -q  && (apt-get -y purge php7.2-*  ) || true
+RUN dpkg --get-selections |grep -v deinstall|grep php7.3- -q  && (apt-get -y purge php7.3-*  ) || true
+
+#RUN  apt-get purge libappstream3 
+RUN apt-key adv --recv-keys --keyserver keys.gnupg.net EF0F382A1A7B6500
+
+#RUN apt-get update && apt-get -y install --no-install-recommends apt-transport-https lsb-release ca-certificates 
+#RUN curl https://packages.sury.org/php/apt.gpg | apt-key add -
+#RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
+#RUN (echo "deb http://archive.debian.org/debian/ squeeze contrib main non-free" ; 
+#RUN (echo "deb http://ftp.debian.org/debian/ jessie main";echo "deb http://security.debian.org/ jessie/updates main" )   >> /etc/apt/sources.list
+
+RUN apt-get update && apt-get upgrade -y --force-yes && apt-get install -y --force-yes openssh-sftp-server nano cron zip tar php5.6-cgi php5.6-gd php5.6-imagick php5.6-common php5.6-curl php5.6-dev php5.6-gd php5.6-imap php5.6-intl php5.6-json php5.6-ldap php5.6-mcrypt php5.6-mysql php5.6-pgsql php5.6-sqlite libapache2-mod-php5.6 php5.6-mbstring php5.6-cgi php5.6-cli php5.6-common php5.6-curl php5.6-gd php5.6-intl php5.6-json php5.6-ldap php5.6-mbstring php5.6-mcrypt php5.6-mongodb php5.6-mysql php5.6-opcache php5.6-readline php5.6-sqlite3 php5.6-tidy php5.6-xml php5.6-zip php5.6-bcmath  supervisor dropbear-run dropbear-bin wget curl rsync nano vim psmisc procps git cron  msmtp-mta msmtp && apt-get clean &&  rm /var/lib/apt/lists/*_*
+
+## OVERWRITTEN IN RUN.sh if APP_TIMEZONE set
+RUN /bin/ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime 
+
+##ENABLE MODULES 
+RUN a2enmod actions alias setenvif proxy ssl proxy_http remoteip rewrite expires
+## SELECT mpm_prefork ## only libapache-mod-php
+RUN a2dismod mpm_event mpm_worker && a2enmod mpm_prefork 
+## SELECT mpm_event ## only FPM
+#RUN a2dismod mpm_prefork mpm_worker && a2enmod mpm_event
+##ENABLE SITES
+RUN a2ensite default-ssl && a2ensite 000-default && ls -lh /etc/apache2/sites*/*
+
+##MCRYPT ## was in php until 7.1
+#RUN echo INSTALL php-mcrypt && pecl channel-update pecl.php.net && pecl install mcrypt-1.0.0 && phpenmod mcrypt 
+RUN echo INSTALL php-mcrypt && apt-get install php5.6-mcrypt && phpenmod mcrypt 
+
+
+##SERVICES
+ARG INSTALL_MARIADB 
+ARG INSTALL_MONGODB 
+ARG INSTALL_RABBITMQ 
+ARG INSTALL_REDIS
+ARG INSTALL_SWISH
+ARG INSTALL_IMAGICK
+ARG INSTALL_NPM
+
+ARG INSTALL_MARIADB=false
+ARG INSTALL_MONGODB=false
+ARG INSTALL_RABBITMQ=false
+ARG INSTALL_REDIS=false
+ARG INSTALL_SWISH=false
+ARG INSTALL_IMAGICK=false
+ARG INSTALL_NPM=false
+
+RUN if [ "${INSTALL_MARIADB}" = "true" ]; then apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 && add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirrors.n-ix.net/mariadb/repo/10.3/ubuntu bionic main' && apt-get update && export DEBIAN_FRONTEND=noninteractive &&  apt-get -y install --no-install-recommends mariadb-server mariadb-client;else echo "NOT INSTALLING MYSQL(mariadb), set INSTALL_MARIADB=true in .env to install ";echo VALUE IS ;echo "${INSTALL_MARIADB}"; fi
+RUN if [ "${INSTALL_MONGODB}" = "true" ]; then apt-get -y install --no-install-recommends mongodb-server mongodb-clients;else echo "NOT INSTALLING MONGODB, set INSTALL_MONGODB=true in .env to install "; fi
+RUN if [ "${INSTALL_RABBITMQ}" = "true" ]; then apt-get -y install --no-install-recommends rabbitmq-server ;else echo "NOT INSTALLING RABBITMQ, set INSTALL_RABBITMQ=true in .env to install "; fi
+RUN if [ "${INSTALL_REDIS}" = "true" ]; then apt-get -y install --no-install-recommends redis-server redis-sentinel redis-tools ;else echo "NOT INSTALLING REDIS, set INSTALL_REDIS=true in .env to install "; fi
+RUN if [ "${INSTALL_SWISH}" = "true" ]; then apt-get -y install --no-install-recommends swish-e ;else echo "NOT INSTALLING swish-e, set INSTALL_SWISH=true in .env to install "; fi
+RUN if [ "${INSTALL_IMAGICK}" = "true" ]; then apt-get -y install --no-install-recommends imagemagick ;else echo "NOT INSTALLING imagemagick, set INSTALL_IMAGICK=true in .env to install "; fi
+RUN if [ "${INSTALL_IMAGICK}" = "true" ]; then apt-get -y install --no-install-recommends npm ;else echo "NOT INSTALLING npm, set INSTALL_NPM=true in .env to install "; fi
+
+
+RUN apt-get install  -y ssl-cert mariadb-client lftp iputils-ping less byobu net-tools lsof iotop iftop sysstat atop nmon
+
+##OPCACHE
+RUN mkdir -p /etc/php/5.6/cli/conf.d /etc/php/5.6/fpm/conf.d /etc/php/5.6/apache2/conf.d /etc/php/5.6/mods-available/
+
+RUN { \
+                echo 'opcache.memory_consumption=128'; \
+                echo 'opcache.interned_strings_buffer=8'; \
+                echo 'opcache.max_accelerated_files=4000'; \
+                echo 'opcache.revalidate_freq=60'; \
+                echo 'opcache.fast_shutdown=1'; \
+                echo 'opcache.enable_cli=1'; \
+        } | tee -a /etc/php/5.6/fpm/conf.d/opcache.ini /etc/php/5.6/apache2/conf.d/opcache.ini /etc/php/5.6/cli/conf.d/opcache.ini /etc/php/5.6/mods-available/opcache.ini > /dev/null
+
+##cleanup stage
+RUN apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes --allow-remove-essential nodejs nodejs-dev dbus make autoconf g++ gcc cpp  e2fsprogs python-dbus gnupg-agent build-essential build-essential software-properties-common )  && apt-get autoremove -y --force-yes &&  apt-get clean &&  rm /var/lib/apt/lists/*_*
+##remove ssh host keys
+RUN  ( test -f /etc/dropbear/dropbear_dss_host_key &&  rm /etc/dropbear/dropbear_dss_host_key ; true )
+RUN  ( test -f /etc/dropbear/dropbear_rsa_host_key &&  rm /etc/dropbear/dropbear_rsa_host_key ; true )
+RUN  ( test -f /etc/dropbear/dropbear_ecdsa_host_key &&  rm  /etc/dropbear/dropbear_ecdsa_host_key ; true) 
+##align docroot to /var/www/html
+RUN sed 's/DocumentRoot \/var\/www$/DocumentRoot \/var\/www\/html/g' /etc/apache2/sites-enabled/* -i
+##log other vhosts to access.log
+RUN ( test -f /etc/apache2/conf-enabled/other-vhosts-access-log.conf && sed 's/other_vhosts_access.log/access.log/g' -i /etc/apache2/conf-enabled/other-vhosts-access-log.conf ;true  )
+
+RUN sed 's/\/VirtualHost/Directory "\/var\/www">\n     Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch\n    AllowOverride All\n    AddType application\/x-httpd-php .htm .html .php5 #.php4\n     AddHandler application\/x-httpd-php .html .htm .php5 #.php4\n<\/Directory>\n     php_admin_value error_log ${APACHE_LOG_DIR}\/php.error.log\n      php_value include_path \/var\/www\/\include_local:\/var\/www\/include\n     <\/VirtualHost/g;s/ErrorLog.\+//g;s/CustomLog.\+/LogFormat "%h %l %u %t \\"%r\\" %>s %b \\"%{Referer}i\\" \\"%{User-Agent}i\\"" combined\n                LogFormat "%{X-Forwarded-For}i %l %u %t \\"%r\\" %>s %b \\"%{Referer}i\\" \\"%{User-Agent}i\\"" proxy          \n                SetEnvIf X-Forwarded-For "^.*\\..*\\..*\\..*" forwarded\n                ErrorLog ${APACHE_LOG_DIR}\/error.log\n                CustomLog ${APACHE_LOG_DIR}\/access.log combined env=!forwarded \n                CustomLog ${APACHE_LOG_DIR}\/access.log proxy env=forwarded\n/g' -i /etc/apache2/sites-available/default-ssl.conf /etc/apache2/sites-available/000-default.conf && \
+		cp -aurv /etc/apache2/sites-available/ /etc/apache2/sites-available.default ;ln -sf /etc/apache2/sites-available/* /etc/apache2/sites-enabled/
+
+#disable catchall document root
+RUN sed 's/.\+DocumentRoot.\+//g' -i /etc/apache2/apache2.conf
+
+#EXPOSE 80
+EXPOSE 443
+
+##fixx www-data userid and only enable sftp for them (bind mount /etc/shells and run "usermod -s /bin/bash www-data" for www-data user login )
+RUN sed 's/^www-data:x:1000/www-data:x:33/g' /etc/passwd -i
+RUN usermod -s /usr/lib/openssh/sftp-server www-data && echo /usr/lib/openssh/sftp-server >> /etc/shells
+
+##userdirs
+RUN ln -s /var/www/html /root/ &&  mkdir -p /var/www/.ssh /var/www/include /var/www/include_local && chown www-data /var/www/ -R && mkdir /root/.ssh && touch /root/.ssh/authorized_keys 
+RUN touch /var/www/.ssh/authorized_keys && chown root:root /var/www/.ssh /var/www/.ssh/authorized_keys && chmod go-rw  /root/.ssh/authorized_keys /root/.ssh /var/www/.ssh /var/www/.ssh/authorized_keys
+
+COPY msmtp-cron-sendmail/sendmail /usr/sbin/sendmail.cron
+RUN chmod +x /usr/sbin/sendmail.cron
+
+COPY run-dropbear.sh /usr/local/bin/run.sh
+RUN chmod +x /usr/local/bin/run.sh
+RUN /bin/bash -c "date -u +%Y-%m-%d_%H.%M |tee -a /etc/container-build-time"
+WORKDIR /var/www
+HEALTHCHECK CMD curl --fail -kL https://127.0.0.1/ || exit 1
+CMD ["/usr/local/bin/run.sh"]
