+++↑↑↑

diff --git a/build/Dockerfile-php7.4-dropbear-fpm b/build/Dockerfile-php7.4-dropbear-fpm
--- a/build/Dockerfile-php7.4-dropbear-fpm
+++ b/build/Dockerfile-php7.4-dropbear-fpm
@@ -3,7 +3,7 @@ FROM ubuntu:bionic
 
 ARG APP_AUTOAPTPROXY
 RUN if [ "${APP_AUTOAPTPROXY}" = "true" ]; then export ENV=debug;echo "auto-apt-proxy ENABLED AT BUILD";else echo "NO APT PROXY (set APP_AUTOAPTPROXY=true in .env to activate)"; fi
-RUN if [ "${APP_AUTOAPTPROXY}" = "true" ]; then apt-get update &&  apt-get autoremove -y --force-yes &&  /bin/bash /root/.bin/docker-install.sh qclean  ;fi
+RUN if [ "${APP_AUTOAPTPROXY}" = "true" ]; then apt-get update &&  apt-get autoremove -y --force-yes &&  /bin/bash /i.sh qclean  ;fi
 ARG APP_AUTOAPTPROXY=false
 
 ARG APT_HTTP_PROXY_URL
@@ -12,6 +12,7 @@ RUN if [ "x$APT_HTTP_PROXY_URL" = "x" ] ; then echo Argument not provided ;else 
 RUN /bin/mkdir -p /root/.bin/
 COPY docker-install.sh /root/.bin/
 RUN ln -s /root/.bin/docker-install.sh /i.sh
+###need gpg-agent and drmngr for apt-key
 RUN /bin/bash /i.sh fixapt && apt-get update  &&   apt-get dist-upgrade -y || true &&  apt-get install -y  --no-install-recommends  dirmngr software-properties-common || true && /bin/bash /i.sh fullclean
 
 ## OVERWRITTEN IN RUN.sh if APP_TIMEZONE set
@@ -21,35 +22,13 @@ ARG APP_DEBUG
 RUN if [ "${APP_DEBUG}" = "true" ]; then export ENV=debug;echo "DEBUG MODE ACTIVATED AT BUILD";else echo "NORMAL MODE (set APP_DEBUG=true in .env to activate)"; fi
 ARG APP_DEBUG=false
 
+##########
+## the following adds ppa's and installs the destined php version
+RUN  export  LC_ALL=C.UTF-8 && apt-get update && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php  && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/apache2 && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/pkg-gearman && /bin/bash /i.sh fixapt && apt-get update &&  apt-get install -y --no-install-recommends php7.4 php7.4-cli || true &&  apt-get autoremove -y --force-yes || true &&  /bin/bash /i.sh fullclean
+##########
 
-RUN  export  LC_ALL=C.UTF-8 && apt-get update && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php  && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/apache2 && LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/pkg-gearman && /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update &&  apt-get install -y --no-install-recommends php7.4 php7.4-cli || true &&  apt-get autoremove -y --force-yes || true &&  /bin/bash /root/.bin/docker-install.sh fullclean
-
-RUN apt-get update  && apt-get dist-upgrade -y &&  apt-get install -y --no-install-recommends \
-      apache2 zip tar \
-      openssh-sftp-server supervisor dropbear-run dropbear-bin wget curl ca-certificates rsync nano \
-      vim psmisc procps git curl  cron php-pear msmtp msmtp-mta &&  apt-get autoremove -y --force-yes || true &&  /bin/bash /root/.bin/docker-install.sh fullclean
-
-RUN apt-get update  &&  apt-get install -y --no-install-recommends curl ca-certificates && /usr/bin/curl -sS https://getcomposer.org/installer -o /tmp/composer.installer.php && php /tmp/composer.installer.php --install-dir=/usr/local/bin --filename=composer && rm /tmp/composer.installer.php &&  /bin/bash /root/.bin/docker-install.sh fullclean
-##ENABLE MODULES
-RUN a2dismod php7.4 || true && a2dismod  mpm_prefork mpm_worker && a2enmod actions alias proxy_fcgi setenvif proxy ssl proxy_http remoteip rewrite expires
-## SELECT mpm_prefork ## only libapache-mod-php
-#RUN a2dismod mpm_event mpm_worker && a2enmod mpm_prefork
-## SELECT mpm_event ## only FPM
-RUN a2dismod mpm_prefork mpm_worker && a2enmod mpm_event
-
-##ENABLE SITES
-RUN a2ensite default-ssl && a2ensite 000-default && ls -lh /etc/apache2/sites*/*
-
-#######
-
-##DROPBEAR MANUAL INSTALL STAGE ( ubuntu source sometimes too old , weak ciphers disabling necessary)
-RUN /bin/bash /root/.bin/docker-install.sh dropbear
-
-##without php-cli , this step will fail ( version detection )
-RUN /bin/bash /root/.bin/docker-install.sh php-fpm
-
-###need gpg-agent and drmngr for apt-key
-RUN apt-get update && apt-get install -y --no-install-recommends gnupg-agent dirmngr && /bin/bash /root/.bin/docker-install.sh fixapt && /bin/bash /root/.bin/docker-install.sh fullclean
+##without php-cli , first step will fail ( version detection ),  second part is #DROPBEAR MANUAL INSTALL STAGE ( ubuntu source sometimes too old , weak ciphers disabling necessary)
+RUN /bin/bash /i.sh php-fpm && /bin/bash /i.sh dropbear
 
 ##  systemd hurts and prevents configuration of certain packages, it will not easily run as it does hav PID 1 so we just let it say systemtrue and let it rot
 RUN test -f /bin/systemctl  && ( rm /bin/systemctl && dpkg-divert --add /bin/systemctl && ln -sT /bin/true /bin/systemctl ) || true
@@ -74,28 +53,31 @@ ARG INSTALL_RABBITMQ=false
 
 RUN echo "installer selection: mariadb:"${INSTALL_MARIADB}" mongodb: "${INSTALL_MONGODB}" RABBITMQ: "${INSTALL_RABBITMQ}" IMAGICK:"${INSTALL_IMAGICK}
 
-RUN if [ "${INSTALL_IMAGICK}" = "true"   ]; then echo "+Imagick"; /bin/bash /root/.bin/docker-install.sh imagemagick && /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update &&  /bin/bash /root/.bin/docker-install.sh fullclean   ; else echo "NOT INSTALLING imagemagick, set INSTALL_IMAGICK=true in .env to install "; fi
-RUN if [ "${INSTALL_MARIADB}" = "true"   ]; then apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 && LC_ALL=C.UTF-8 add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirrors.n-ix.net/mariadb/repo/10.3/ubuntu bionic main' && apt-get update && export DEBIAN_FRONTEND=noninteractive &&  apt-get -y install --no-install-recommends mariadb-server mariadb-client &&  /bin/bash /root/.bin/docker-install.sh fullclean  ;else echo "NOT INSTALLING MYSQL(mariadb), set INSTALL_MARIADB=true in .env to install ";echo VALUE IS ;echo "${INSTALL_MARIADB}"; fi
-RUN if [ "${INSTALL_MONGODB}" = "true"   ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends mongodb-server mongodb-clients &&  /bin/bash /root/.bin/docker-install.sh fullclean  ;else echo "NOT INSTALLING MONGODB, set INSTALL_MONGODB=true in .env to install "; fi
-RUN if [ "${INSTALL_REDIS}" = "true"     ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends redis-server redis-sentinel redis-tools &&  /bin/bash /root/.bin/docker-install.sh fullclean   ;else echo "NOT INSTALLING REDIS, set INSTALL_REDIS=true in .env to install "; fi
+RUN if [ "${INSTALL_IMAGICK}" = "true"   ]; then echo "+Imagick"; /bin/bash /i.sh imagemagick && /bin/bash /i.sh fixapt && apt-get update &&  /bin/bash /i.sh fullclean   ; else echo "NOT INSTALLING imagemagick, set INSTALL_IMAGICK=true in .env to install "; fi
+RUN if [ "${INSTALL_MARIADB}" = "true"   ]; then apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8 && LC_ALL=C.UTF-8 add-apt-repository 'deb [arch=amd64,arm64,ppc64el] http://mirrors.n-ix.net/mariadb/repo/10.3/ubuntu bionic main' && apt-get update && export DEBIAN_FRONTEND=noninteractive &&  apt-get -y install --no-install-recommends mariadb-server mariadb-client &&  /bin/bash /i.sh fullclean  ;else echo "NOT INSTALLING MYSQL(mariadb), set INSTALL_MARIADB=true in .env to install ";echo VALUE IS ;echo "${INSTALL_MARIADB}"; fi
+RUN if [ "${INSTALL_MONGODB}" = "true"   ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends mongodb-server mongodb-clients &&  /bin/bash /i.sh fullclean  ;else echo "NOT INSTALLING MONGODB, set INSTALL_MONGODB=true in .env to install "; fi
+RUN if [ "${INSTALL_REDIS}" = "true"     ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends redis-server redis-sentinel redis-tools &&  /bin/bash /i.sh fullclean   ;else echo "NOT INSTALLING REDIS, set INSTALL_REDIS=true in .env to install "; fi
 RUN if [ "${INSTALL_NPM}" = "true"       ]; then apt-get update && apt-get -y install --no-install-recommends npm ;else echo "NOT INSTALLING npm, set INSTALL_NPM=true in .env to install "; fi
 
-RUN if [ "${INSTALL_RABBITMQ}" = "true"  ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends rabbitmq-server &&  /bin/bash /root/.bin/docker-install.sh fullclean   ;else echo "NOT INSTALLING RABBITMQ, set INSTALL_RABBITMQ=true in .env to install "; fi
+RUN if [ "${INSTALL_RABBITMQ}" = "true"  ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends rabbitmq-server &&  /bin/bash /i.sh fullclean   ;else echo "NOT INSTALLING RABBITMQ, set INSTALL_RABBITMQ=true in .env to install "; fi
 
-#### RUN if [ "${INSTALL_SWISH}" = "true"     ]; then  /bin/bash /root/.bin/docker-install.sh fixapt && apt-get update && apt-get -y install --no-install-recommends swish-e &&  /bin/bash /root/.bin/docker-install.sh fullclean  ;else echo "NOT INSTALLING swish-e, set INSTALL_SWISH=true in .env to install "; fi
+#### RUN if [ "${INSTALL_SWISH}" = "true"     ]; then  /bin/bash /i.sh fixapt && apt-get update && apt-get -y install --no-install-recommends swish-e &&  /bin/bash /i.sh fullclean  ;else echo "NOT INSTALLING swish-e, set INSTALL_SWISH=true in .env to install "; fi
 
+#######
+COPY pool-www.conf /root/www.conf
+#######
 
-RUN /bin/bash /root/.bin/docker-install.sh util
+COPY run-dropbear.sh /usr/local/bin/run.sh
+COPY supervisord.conf /etc/supervisor/supervisord.conf
+COPY run-apache.sh /run-apache.sh
+RUN chmod +x /usr/local/bin/run.sh
+ 
+## INSTALL UTiLS , Fix Apache , rectify www-data , fpm socket etc
+RUN /bin/bash /i.sh util && /bin/bash /i.sh apache &&  /bin/bash /i.sh wwwdata
 
 
 ##cleanup stage will be always executed due to random file , so upgrades happen every build ( no docker cache)
-RUN head -c 5 /dev/random > ignore_this_file && apt-get update && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  e2fsprogs python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev )
-RUN /bin/bash /i.sh cleanup
-
-###FIX apache
-RUN /bin/bash /i.sh apache
-
-RUN /bin/bash /i.sh wwwdata
+RUN head -c 5 /dev/random > ignore_this_file && apt-get update && apt-get dist-upgrade -y --force-yes &&  (( sleep 2;echo 'Yes, do as I say!') |apt-get purge -y --force-yes shared-mime-info eject initramfs-tools nodejs nodejs-dev dbus make autoconf g++ gcc cpp  e2fsprogs python-dbus gnupg-agent build-essential build-essential software-properties-common libc-dev ) && /bin/bash /i.sh cleanup
 
 #EXPOSE 80
 EXPOSE 443
@@ -104,20 +86,8 @@ EXPOSE 443
 COPY msmtp-cron-sendmail/sendmail /usr/sbin/sendmail.cron
 RUN chmod +x /usr/sbin/sendmail.cron
 
-COPY pool-www.conf /etc/php/7.4/fpm/pool.d/www.conf
 
-COPY run-dropbear.sh /usr/local/bin/run.sh
-COPY supervisord.conf /etc/supervisor/supervisord.conf
-COPY run-apache.sh /run-apache.sh
-
-RUN chmod +x /usr/local/bin/run.sh
-
-RUN /bin/mkdir -p /var/run/php/
-
-RUN sed 's/exec service cron start/exec service php7.4-fpm start \&\nexec service cron start/g' /usr/local/bin/run.sh -i
-##TODO supervisor
-RUN /bin/bash -c "date -u +%Y-%m-%d_%H.%M |tee -a /etc/container-build-time"
-RUN /bin/bash -c "test -f /etc/apt/apt.conf.d/10-proxy && rm /etc/apt/apt.conf.d/10-proxy;true"
+RUN /bin/bash -c "date -u +%Y-%m-%d_%H.%M |tee -a /etc/container-build-time" && /bin/bash -c "test -f /etc/apt/apt.conf.d/10-proxy && rm /etc/apt/apt.conf.d/10-proxy;true"
 WORKDIR /var/www
 HEALTHCHECK CMD /usr/bin/curl--fail -H "User-Agent: docker-health-check/over9000" -kL https://127.0.0.1/ || exit 1
 CMD ["/bin/bash","/usr/local/bin/run.sh"]
